# Don't worry about this file if you're an external contributor
name: vault-plugin-secrets-ejson
display_name: "Vault Plugin: Secrets EJSON"

up:
  - go:
      version: 1.16

commands:
  make:deps:
      syntax: ""
      desc: 'installs dependencies'
      run: make deps
  make:test:
      syntax: ""
      desc: 'run all of the tests'
      run: make test
  make:fmt:
    syntax: ""
    desc: 'runs `go fmt` command to clean up code formatting'
    run: make fmt
  make:build:
    syntax: ""
    desc: 'builds the vault-plugin-secrets-ejson binary'
    run: make build
